name: Build

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install pip dependencies
      run: |
        pip3 install semver luadata
    - name: Install apt dependencies
      run: |
        sudo rm -f /var/lib/man-db/auto-update
        sudo apt install --no-install-recommends lua5.1 p7zip-full
    - name: Write secret to file
      run: |
        cat > secret.jx3dat << 'EOF'
        ${{ secrets.SECRET_JX3DAT }}
        EOF
    - name: Run Build Command
      run: |
        python3 \!src-dist/ci.py
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-archives-${{ github.run_number }}-${{ github.sha }}
        path: '\!src-dist/dist/*.7z'
